<?xml version="1.0"?>
<package format="3">
  <name>rower_description</name>
  <version>0.1.0</version>
  <description>Robot geometry and TF description for the Waveshare UGV02 rower robot.</description>
  <maintainer email="80409749+xander-07@users.noreply.github.com">Alex</maintainer>
  <license>MIT</license>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
